title: PyMemory Challenge
description: Train your brain, one digit at a time.
baseurl: ""        # leave empty for user/organization pages
url: "https://<your-github-username>.github.io/<repo-name>" # optional

remote_theme: clenemt/jackal
plugins:
  - jekyll-remote-theme

# Optional: specify author, social links, etc.
author:
  name: Yana
