title: "Memory Logic Game"
description: "Cute pink memory game"
url: "https://yanalerner10.github.io"
baseurl: "/Memory-logic-game"

theme: jekyll-theme-modernist

plugins:
  - jekyll-feed

include:
  - assets
  - _layouts
